require: rubocop-rspec

inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.3.3
  TargetRailsVersion: 4.2
  Include:
    - '**/Rakefile'
    - '**/*.rb'

Layout/BlockEndNewline:
  Exclude:
    - 'spec/**/*'

Layout/MultilineBlockLayout:
  Exclude:
    - 'spec/**/*'

Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context']

Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

RSpec/ExampleLength:
  Enabled: false

Style/LineEndConcatenation:
  Enabled: false
